// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: b0Builder,
      ),
    ];

const routePaths = (
  path: '/',
  splash: '/splash',
);
