// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/pokemon/[id]',
        uri: Uri.parse('/pokemon/[id]'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/type',
        uri: Uri.parse('/type'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: b2Builder,
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: b3Builder,
      ),
    ];

const routePaths = (
  path: '/',
  pokemon: (
    path: '/pokemon',
    $id: '/pokemon/[id]',
  ),
  type: '/type',
  splash: '/splash',
  home: '/home',
);
